### ISSUE TITLE
Line width option for `quick_map`

### ISSUE THREAD

**Issue by zmoon** [noaa-oar-arl/MONET#133]
Hi, 

I was wondering whether it would be possible to add an argument to the quick_map function to enable the user to specify the linewidth for the country outlines?

Many Thanks, 

Annie

_Originally posted by @annalisasheehan in https://github.com/noaa-oar-arl/monet/issues/92#issuecomment-1532982493_

**Comment by bbakernoaa** [comment]
@zmoon lets make this an option to set the linewidths as a `kwarg`

**Comment by zmoon** [comment]
Looks you can already specify this with `map_kws` dict, e.g.
```python
da.monet.quick_map(map_kws=dict(linewidth=2))
```
@bbakernoaa do we still want to support a standalone kwarg?

**Comment by bbakernoaa** [comment]
@zmoon well look at me! I think that this is the way I envision it. I don't want to add a specific `linewidth` outside of `map_kws` as I see it as directly effecting the linewidths of the cartopy lines.

**Comment by zmoon** [comment]
@annalisasheehan are you happy this solution?

**Comment by annalisasheehan** [comment]
That's great, thank you both!
