### ISSUE TITLE
Requirements for Model's and 2d Observations

### ISSUE THREAD

**Issue by bbakernoaa** [noaa-oar-arl/monet#14]
## Requirements for Model's and 2D Observations

Requirements for new multidimensional objects 

- All datasests should be store as a xarray dataset or opened as an xarray dataarray. 
- If the data can be retrieved via opendap or ftp a method should be created to do so. 
- All model data should be opened with a method called dataobj.open_dataset(....) which returns the xarray object
- Units are required for all fields and should be stored as an attribute.  The units need to be converted to: 
    - Kelvin
    - ppbv
    - dobson
    - ug/m3
    - w/m2
    - m/s 
    - etc.....

- All datasets should include the latitude and longitude as coordinates in the xarray dataset with dimensions (y,x)

- dimensions should have the names x,y,z, and time where time is the GMT date

**Comment by amcz** [comment]
There was an _dataset_to_monet function in the monet_accessor which was useful for getting xarrays in the proper format. Is there a replacement function or has it been moved to another location?

**Comment by bbakernoaa** [comment]
This function still exists.  It is in monet.dataset_to_monet or the function will apply to most datasets without any issues (ie when you call the monet functions it tries to apply the function automagically).

**Comment by zmoon** [comment]
Moved to https://github.com/noaa-oar-arl/monetio/wiki
