### ISSUE TITLE
API Reference not working on readthedocs

### ISSUE THREAD

**Issue by fsenf** [noaa-oar-arl/monet#81]
Hi all,

I guess, you are aware, but API reference documentation is not working on readthedocs. I will have a look on it.

Readthedocs:
* needs to `import monet` module
* it therefore builds a docker image and installs all required package ( a `docs/requirement` file is helpful )
* after import it tries to resolve all functions

Cheers, Fabian

**Comment by bbakernoaa** [comment]
@fsenf This is awesome.  Thanks for helping with this.  I've merged the changes into my master branch and the docs built successfully :)

**Comment by bbakernoaa** [comment]
It appears to be missing a few of the .rst files.  When I did the restructuring last month I broke the docs.  sorry

**Comment by fsenf** [comment]
Great to see.!

The issue comes with the `cartopy` module.  
* Installation wiht `pip`does work because it needs some external libraries. 
* I tried RTD configuraiton with conda. In this case, I got memory consumption problems (RTD user limit).
* The best way that the moment is to "mock" the `cartopy` module in the `conf.py`
