### ISSUE TITLE
interp_constant_lat and lon

### ISSUE THREAD

**Issue by amcz** [noaa-oar-arl/monet#84]
interp_constant_lat and interp_constant_lon returning unexpected results.

line 828  dims=['lat','lon']  should be changed to dims=['lon','lat']
line 833, 1736 result.isel(x=0) should be changed to result.isel(y=0) to return constant latitude
line 873, 1696 result.isel(y=0) should be changed to result.isel(x=0) to return constant longitude.

**Comment by bbakernoaa** [comment]
Good catch. I’ll look into it tomorrow morning 

Just making a note here for the code line https://github.com/noaa-oar-arl/monet/blob/master/monet/monet_accessor.py#L791
