### ISSUE TITLE
no module named sat

### ISSUE THREAD

**Issue by joemcglinchy** [noaa-oar-arl/monet#88]
Hello,

after installing `monet` with the command `conda install -c conda-forge monet`, the command `from monet.sat import nesdis_edr_viirs` produces an attribute error `ModuleNotFoundError: No module named 'monet.sat'`.

I don't see a sat.py module in the `monet` folder on the github repo, just wondering how to use this capability and what other capabilities may be available in the 'sat' module? Executing `dir(monet)` returns

`['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'dataset_to_monet', 'monet_accessor', 'plots', 'rename_latlon', 'rename_to_monet_latlon', 'savefig', 'util']`

Running Windows 10, python 3.6.7. Also see the error on python 3.8.2.

**Comment by bbakernoaa** [comment]
@joemcglinchy monet recently underwent a change with v2.2.0.  The I/O portion of monet has been moved to a separate repository.  https://github.com/noaa-oar-arl/monetio

monetio can also be installed with conda 

`conda install -c conda-forge monetio`

then `from monetio.sat import nests_edr_viirs`

**Comment by joemcglinchy** [comment]
thank you for the quick response @bbakernoaa! I installed `monetio` and had no problem with that import.

**Comment by bbakernoaa** [comment]
That’s great! Thanks for using MONET. please post if anything changes else that comes up.
